import type { TaskInterface } from '@/interfaces/TaskInterface';

/**
 * Mock tasks preloaded on first load, per the MVP's LocalStorage-only scope.
 *
 * Every `projectId` points at a project in the project seeder, and every
 * `assigneeId` at a user who is a member of that same project: TaskService
 * only offers a project's members as assignees, so seeded data has to obey the
 * same rule the forms enforce.
 *
 * `sprintId` is null on every row. Sprints have no store or service yet, so
 * pointing a task at 'SPR-08' would be a dangling reference the app cannot
 * resolve. The sprint slice fills these in.
 */
export const taskSeeder: TaskInterface[] = [
  // PRJ-01 — Mobile App Redesign. Members: USR-01, USR-02.
  {
    id: 'TSK-01',
    title: 'Design the onboarding flow',
    description: 'Wireframes and final screens for the sign-up sequence.',
    type: 'feature',
    storyPoints: 5,
    priority: 'high',
    status: 'done',
    createdAt: '2026-02-04',
    dueDate: '2026-02-14',
    projectId: 'PRJ-01',
    sprintId: null,
    assigneeId: 'USR-02',
  },
  {
    id: 'TSK-02',
    title: 'Build the reusable button set',
    description: 'Primary, secondary and destructive variants.',
    type: 'feature',
    storyPoints: 3,
    priority: 'medium',
    status: 'done',
    createdAt: '2026-02-05',
    dueDate: '2026-02-16',
    projectId: 'PRJ-01',
    sprintId: null,
    assigneeId: 'USR-01',
  },
  {
    id: 'TSK-03',
    title: 'Fix the session timeout crash',
    description: 'The app closes when the token expires while offline.',
    type: 'bug',
    storyPoints: 2,
    priority: 'critical',
    status: 'in_progress',
    createdAt: '2026-02-10',
    dueDate: '2026-02-20',
    projectId: 'PRJ-01',
    sprintId: null,
    assigneeId: 'USR-02',
  },
  {
    id: 'TSK-04',
    title: 'Email verification screen',
    description: 'Confirmation code entry and resend flow.',
    type: 'feature',
    storyPoints: 8,
    priority: 'medium',
    status: 'todo',
    createdAt: '2026-02-11',
    dueDate: '2026-03-02',
    projectId: 'PRJ-01',
    sprintId: null,
    assigneeId: null,
  },
  {
    id: 'TSK-05',
    title: 'Update the icon assets',
    description: 'Replace the legacy PNG set with SVG.',
    type: 'chore',
    storyPoints: 1,
    priority: 'low',
    status: 'todo',
    createdAt: '2026-02-12',
    dueDate: null,
    projectId: 'PRJ-01',
    sprintId: null,
    assigneeId: 'USR-01',
  },

  // PRJ-02 — Customer Portal. Members: USR-03.
  {
    id: 'TSK-06',
    title: 'Billing history table',
    description: 'Paginated list of past invoices.',
    type: 'feature',
    storyPoints: 5,
    priority: 'high',
    status: 'done',
    createdAt: '2026-03-19',
    dueDate: '2026-03-30',
    projectId: 'PRJ-02',
    sprintId: null,
    assigneeId: 'USR-03',
  },
  {
    id: 'TSK-07',
    title: 'Evaluate payment providers',
    description: 'Compare fees and integration effort for three vendors.',
    type: 'research',
    storyPoints: 3,
    priority: 'medium',
    status: 'in_progress',
    createdAt: '2026-03-20',
    dueDate: '2026-04-03',
    projectId: 'PRJ-02',
    sprintId: null,
    assigneeId: 'USR-03',
  },
  {
    id: 'TSK-08',
    title: 'Account self-service settings',
    description: 'Let customers update their contact details.',
    type: 'feature',
    storyPoints: 5,
    priority: 'high',
    status: 'todo',
    createdAt: '2026-03-22',
    dueDate: null,
    projectId: 'PRJ-02',
    sprintId: null,
    assigneeId: null,
  },

  // PRJ-03 — Cloud Migration. Members: USR-03, USR-02.
  {
    id: 'TSK-09',
    title: 'Migrate the legacy database',
    description: 'Move the on-premise instance to the managed service.',
    type: 'chore',
    storyPoints: 8,
    priority: 'critical',
    status: 'in_progress',
    createdAt: '2026-01-08',
    dueDate: '2026-02-28',
    projectId: 'PRJ-03',
    sprintId: null,
    assigneeId: 'USR-03',
  },
  {
    id: 'TSK-10',
    title: 'Fix the broken deploy pipeline',
    description: 'Staging builds fail after the runner upgrade.',
    type: 'bug',
    storyPoints: 3,
    priority: 'high',
    status: 'todo',
    createdAt: '2026-01-15',
    dueDate: '2026-02-05',
    projectId: 'PRJ-03',
    sprintId: null,
    assigneeId: 'USR-02',
  },
  {
    id: 'TSK-11',
    title: 'Document the rollback procedure',
    description: 'Step-by-step guide for reverting a failed release.',
    type: 'chore',
    storyPoints: 2,
    priority: 'low',
    status: 'done',
    createdAt: '2026-01-20',
    dueDate: '2026-01-31',
    projectId: 'PRJ-03',
    sprintId: null,
    assigneeId: 'USR-02',
  },

  // PRJ-04 — Loyalty Program. Members: USR-01. Closed project, all tasks done.
  {
    id: 'TSK-12',
    title: 'Points accrual rules',
    description: 'Define how purchases translate into points.',
    type: 'feature',
    storyPoints: 5,
    priority: 'medium',
    status: 'done',
    createdAt: '2025-09-12',
    dueDate: '2025-09-30',
    projectId: 'PRJ-04',
    sprintId: null,
    assigneeId: 'USR-01',
  },
  {
    id: 'TSK-13',
    title: 'Rewards catalogue screen',
    description: 'Browse and redeem available rewards.',
    type: 'feature',
    storyPoints: 3,
    priority: 'low',
    status: 'done',
    createdAt: '2025-09-15',
    dueDate: '2025-10-10',
    projectId: 'PRJ-04',
    sprintId: null,
    assigneeId: 'USR-01',
  },
];
